# Generated by Django 4.0.4 on 2022-05-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='TodolistForm',
        ),
    ]
