# Generated by Django 4.0.4 on 2022-05-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_database_todolistform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistform',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='todolistform',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='todolistform',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
