# Generated by Django 4.0.4 on 2022-05-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_todolistform_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistform',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='todolistform',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
