# Generated by Django 4.0.4 on 2022-05-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_first_name_todolistform_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistform',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
