# Generated by Django 4.0.4 on 2022-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rename_lastname_todolistform_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('serialnumber', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_content', models.TextField()),
                ('blog_slug', models.CharField(max_length=100)),
                ('blog_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
