# Generated by Django 4.0.4 on 2022-05-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRFapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_title', models.CharField(max_length=200)),
                ('api_content', models.TextField()),
                ('api_slug', models.CharField(max_length=100)),
                ('api_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
