# Generated by Django 4.0.4 on 2022-05-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_drfapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DRFapi',
        ),
    ]
